// ═══════════════════════════════════════════════════════════════════════════
// Consolidated build/version info — single source of truth for GET /version.
// ═══════════════════════════════════════════════════════════════════════════
//
// Brings together the version signals that previously lived in separate places:
//   - gitSha            → build-injected (server/Dockerfile ARG GIT_SHA + CI --build-arg)
//   - version           → package.json (semver)
//   - calculatorData*   → generated by `npm run version:data` (src/data/calculatorDataVersion.js)
//   - builtAt/deployedAt→ env (optional; deployedAt already used by /capabilities)
//
// Read-only and secret-free by construction: only non-sensitive build metadata.
import { createRequire } from "node:module";
import {
  CALCULATOR_DATA_VERSION,
  CALCULATOR_DATA_VERSION_DATE,
} from "../../src/data/calculatorDataVersion.js";

const require = createRequire(import.meta.url);
const pkg = require("../../package.json");

// Process boot time — proxy for "this instance started at" (uptime baseline).
const STARTED_AT = new Date().toISOString();

/**
 * Build the payload served at GET /version.
 * @returns {{
 *   ok: true, version: string|null, gitSha: string|null,
 *   calculatorDataVersion: string|null, calculatorDataVersionDate: string|null,
 *   builtAt: string|null, deployedAt: string|null, node: string, startedAt: string
 * }}
 */
export function buildVersionInfo() {
  return {
    ok: true,
    version: pkg.version || null,
    gitSha: process.env.GIT_SHA || null,
    calculatorDataVersion: CALCULATOR_DATA_VERSION || null,
    calculatorDataVersionDate: CALCULATOR_DATA_VERSION_DATE || null,
    builtAt: process.env.BUILT_AT || null,
    deployedAt: process.env.DEPLOYED_AT || null,
    node: process.version,
    startedAt: STARTED_AT,
  };
}

export default buildVersionInfo;
